export const dashboardLabels = {
  title: 'Dashboard',
  subtitle: "Yo'nalishlar bo'yicha alohida bloklar",
  blocks: { vocational: 'Kasb kurslari va hududiy taqsimot', otm: 'OTM tayyorlov kurslari va hududiy taqsimot', surveys: "So'rovnoma natijalari" },
  kpi: {
    soldiers: 'Jami askarlar',
    districts: 'Harbiy okruglar',
    otmCandidates: 'OTM nomzodlari',
    institutions: 'Muassasalar',
    contracts: 'Shartnomalar',
    finalized: 'Yakunlangan anketalar',
  },
  charts: {
    completion: "Anketa to'ldirilishi",
    interests: 'Qiziqqan kasb yo\'nalishlari',
    plans: 'Kelgusi rejalar',
    subjectNeeds: 'OTM tayyorgarligi ehtiyoji',
    specialty: 'Ixtisoslik fanlari',
    mandatory: 'Majburiy fanlar',
    education: "Ta'lim darajasi va sertifikatlar",
    courseResults: 'Kurs natijalari',
    soldiersByDistrict: 'Askarlarning hududiy taqsimoti (okruglar kesimida)',
    unitsOfDistrict: (district: string) => `${district}: harbiy qismlar bo'yicha askarlar`,
    otmByDistrict: 'OTMga tayyorlanuvchi askarlar (okruglar kesimida)',
    pickDistrict: "Harbiy qismlar diagrammasini ko'rish uchun okrug ustunini bosing",
    institutionsByRegion: 'Hududlardagi muassasalar va shartnomalar',
    professionChoices: 'Askarlar tanlagan kasblar (yo\'nalishlar)',
    institutions: 'Muassasalar',
    contracts: 'Qism bilan shartnomalar',
  },
  geography: {
    region: 'Hudud',
    soldiers: 'Askarlar',
    institutionsTable: 'Hudud → muassasa → harbiy qism',
    institution: 'Muassasa',
    type: 'Turi',
    units: 'Shartnoma tuzilgan harbiy qismlar',
    noContracts: 'Shartnoma yo\'q',
    contractNo: (no: string) => `shartnoma № ${no}`,
    types: { TECHNICAL_SCHOOL: 'Texnikum', SCHOOL: 'Maktab', TRAINING_CENTER: "O'quv markazi" } as Record<string, string>,
    statuses: { PROPOSED: 'Taklif', UNDER_REVIEW: "Ko'rib chiqilmoqda", APPROVED: 'Tasdiqlangan' } as Record<string, string>,
  },
} as const;
