export const rolePermissionsLabels = {
  title: 'Rol huquqlari',
  subtitle: "SuperAdmin, Admin (okrug) va User (qism) rollari uchun standart ruxsatlar. SuperAdmin ruxsatlarini faqat Mega SuperAdmin o'zgartira oladi; Mega SuperAdmin har doim barcha ruxsatlarga ega",
  group: "Bo'lim",
  lockedRoleHint: "Bu rol ruxsatlarini faqat Mega SuperAdmin o'zgartira oladi",
  selectAll: (role: string) => `${role}: barchasini belgilash`,
  granted: (granted: number, total: number) => `${granted} / ${total}`,
  groups: {
    system: 'Tizim va sozlamalar',
    soldiers: 'Askarlar',
    questionnaires: 'Anketalar',
    deadlines: 'Muddatlar',
    training: "O'quv jarayoni",
    admissions: 'Qabul va bandlik',
    reporting: 'Hisobot va dashboard',
  },
  permission: 'Ruxsat',
  pages: 'Ochadigan sahifalar',
  search: "Ruxsat yoki sahifa bo'yicha qidirish",
  allGroups: "Barcha bo'limlar",
  noMatches: 'Mos ruxsat topilmadi',
  legend: "Mega SuperAdmin har doim barcha ruxsatlarga ega va jadvalda ko'rsatilmaydi. SuperAdmin ustunini faqat Mega SuperAdmin o'zgartira oladi (qulf belgisi). Admin va User ustunlarini SuperAdmin ham o'zgartira oladi. O'zgarishlar «Saqlash» bosilgandan keyin kuchga kiradi; alohida foydalanuvchiga qo'shimcha ruxsatni «Foydalanuvchilar» sahifasida bera olasiz.",
  save: 'Saqlash',
  discard: 'Bekor qilish',
  saved: 'Rol huquqlari saqlandi',
  unsaved: "Saqlanmagan o'zgarishlar bor",
} as const;
