export const rolePermissionsLabels = {
  title: 'Rol huquqlari',
  subtitle: "SuperAdmin, Admin (okrug) va User (qism) rollari uchun standart ruxsatlar. SuperAdmin ruxsatlarini faqat Mega SuperAdmin o'zgartira oladi; Mega SuperAdmin har doim barcha ruxsatlarga ega",
  group: "Bo'lim",
  lockedRoleHint: "Bu rol ruxsatlarini faqat Mega SuperAdmin o'zgartira oladi",
  selectAll: (role: string) => `${role}: barchasini belgilash`,
  granted: (granted: number, total: number) => `${granted} / ${total}`,
  groups: {
    system: 'Tizim va sozlamalar',
    soldiers: 'Askarlar',
    questionnaires: 'Anketalar',
    assignments: 'Biriktirish va muddatlar',
    training: "O'quv jarayoni",
    admissions: 'Qabul va bandlik',
    reporting: 'Hisobot va dashboard',
  },
  permission: 'Ruxsat',
  save: 'Saqlash',
  discard: 'Bekor qilish',
  saved: 'Rol huquqlari saqlandi',
  unsaved: "Saqlanmagan o'zgarishlar bor",
} as const;
