export const authLabels = {
  title: 'Tizimga kirish',
  username: 'Login',
  password: 'Parol',
  usernameRequired: 'Loginni kiriting',
  passwordRequired: 'Parolni kiriting',
  submit: 'Kirish',
  failed: 'Kirib bo\'lmadi',
  sessionExpired: 'Sessiya tugadi. Qaytadan kiring',
  otpLabel: 'Autentifikator kodi (6 xonali)',
  otpRequired: 'Autentifikator ilovasidagi kodni kiriting',
  twoFactor: {
    title: 'Ikki bosqichli autentifikatsiya',
    enabled: 'Yoqilgan',
    disabled: "O'chirilgan",
    setupRequired: 'Sizning rolingiz uchun ikki bosqichli autentifikatsiyani yoqish tavsiya etiladi',
    start: 'Yoqishni boshlash',
    scan: "Autentifikator ilovasi (Google Authenticator va h.k.) bilan QR kodni skanerlang yoki kalitni qo'lda kiriting",
    secret: 'Kalit',
    confirm: 'Kodni tasdiqlash',
    disable: "O'chirish",
    enabledMessage: 'Ikki bosqichli autentifikatsiya yoqildi',
    disabledMessage: "Ikki bosqichli autentifikatsiya o'chirildi",
    code: 'Kod',
  },
  profileTitle: 'Profil',
  demoHint: 'Demo: login — hktb, admin, qomondon1, katta1, psixolog1 …; parol — Parol123!',
} as const;
