export const authLabels = {
  title: 'Tizimga kirish',
  welcome: 'Xush kelibsiz',
  loginSubtitle: 'Hisobingizga kirish uchun login va parolni kiriting',
  brandFeatures: [
    { key: 'soldiers', title: "Yig'ma jild va anketalar", text: "Har bir askarning shaxsiy jildi va kasbiy qiziqish anketasi bir joyda" },
    { key: 'courses', title: 'Kasb va OTM tayyorlov', text: "Guruhlar va kurs natijalarini yuritish" },
    { key: 'monitoring', title: 'Hududiy monitoring', text: "Okrug va qismlar kesimida real vaqt dashboardi" },
  ],
  brandFooter: "Xavfsiz kirish · Barcha amallar audit jurnaliga yoziladi",
  username: 'Login',
  password: 'Parol',
  usernameRequired: 'Loginni kiriting',
  passwordRequired: 'Parolni kiriting',
  submit: 'Kirish',
  failed: 'Kirib bo\'lmadi',
  sessionExpired: 'Sessiya tugadi. Qaytadan kiring',
  profileTitle: 'Profil',
  fullName: 'F.I.Sh.',
  role: 'Rol',
  location: 'Hudud',
  demoHint: 'Demo: login — hktb, admin, qomondon1, katta1, psixolog1 …; parol — Parol123!',
} as const;
