export const authLabels = {
  title: 'Tizimga kirish',
  username: 'Login',
  password: 'Parol',
  usernameRequired: 'Loginni kiriting',
  passwordRequired: 'Parolni kiriting',
  submit: 'Kirish',
  failed: 'Kirib bo\'lmadi',
  sessionExpired: 'Sessiya tugadi. Qaytadan kiring',
  profileTitle: 'Profil',
  fullName: 'F.I.Sh.',
  role: 'Rol',
  location: 'Hudud',
  demoHint: 'Demo: login — hktb, admin, qomondon1, katta1, psixolog1 …; parol — Parol123!',
} as const;
