-- 4 rolli, hududga asoslangan va dinamik sozlanadigan ruxsatlar tizimi.
--   1) locations — foydalanuvchini hududga (respublika / okrug / qism) biriktirish uchun yagona daraxt;
--   2) role_permissions — ADMIN va USER rollari uchun tahrirlanadigan ruxsatlar matritsasi;
--   3) user_permissions — foydalanuvchiga shaxsiy (qo'shimcha) ruxsatlar;
--   4) eski 15 ta rolni yangi 4 ta rolga ko'chirish (eski rolning vakolat darajasi bo'yicha).

-- ---------------------------------------------------------------------------------------------------------
-- 1. Hududlar daraxti
-- ---------------------------------------------------------------------------------------------------------
CREATE TABLE locations (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id            BIGINT REFERENCES locations (id),
    level                VARCHAR(20)  NOT NULL,
    name                 VARCHAR(255) NOT NULL,
    code                 VARCHAR(60),
    military_district_id BIGINT REFERENCES military_districts (id),
    military_unit_id     BIGINT REFERENCES military_units (id),
    CONSTRAINT uq_locations_district UNIQUE (military_district_id),
    CONSTRAINT uq_locations_unit UNIQUE (military_unit_id),
    CONSTRAINT ck_locations_level CHECK (
        (level = 'REPUBLIC' AND parent_id IS NULL AND military_district_id IS NULL AND military_unit_id IS NULL)
        OR (level = 'DISTRICT' AND parent_id IS NOT NULL AND military_district_id IS NOT NULL AND military_unit_id IS NULL)
        OR (level = 'UNIT' AND parent_id IS NOT NULL AND military_district_id IS NULL AND military_unit_id IS NOT NULL))
);

CREATE INDEX ix_locations_parent ON locations (parent_id);

INSERT INTO locations (parent_id, level, name, code)
VALUES (NULL, 'REPUBLIC', 'O''zbekiston Respublikasi', 'UZ');

INSERT INTO locations (parent_id, level, name, code, military_district_id)
SELECT (SELECT r.id FROM locations r WHERE r.level = 'REPUBLIC'), 'DISTRICT', md.name, md.code, md.id
FROM military_districts md;

INSERT INTO locations (parent_id, level, name, code, military_unit_id)
SELECT dl.id, 'UNIT', mu.name, mu.code, mu.id
FROM military_units mu
JOIN locations dl ON dl.military_district_id = mu.military_district_id;

-- ---------------------------------------------------------------------------------------------------------
-- 2. Foydalanuvchilarni hududga biriktirish (military_district_id / military_unit_id -> location_id)
-- ---------------------------------------------------------------------------------------------------------
ALTER TABLE app_users ADD COLUMN location_id BIGINT REFERENCES locations (id);

UPDATE app_users u
SET location_id = (SELECT l.id FROM locations l WHERE l.military_unit_id = u.military_unit_id)
WHERE u.military_unit_id IS NOT NULL;

UPDATE app_users u
SET location_id = (SELECT l.id FROM locations l WHERE l.military_district_id = u.military_district_id)
WHERE u.military_unit_id IS NULL AND u.military_district_id IS NOT NULL;

ALTER TABLE app_users DROP COLUMN military_unit_id;
ALTER TABLE app_users DROP COLUMN military_district_id;

-- ---------------------------------------------------------------------------------------------------------
-- 3. Ruxsatlar jadvallari
-- ---------------------------------------------------------------------------------------------------------
CREATE TABLE role_permissions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role       VARCHAR(40) NOT NULL,
    permission VARCHAR(60) NOT NULL,
    CONSTRAINT uq_role_permission UNIQUE (role, permission)
);

CREATE TABLE user_permissions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES app_users (id) ON DELETE CASCADE,
    permission VARCHAR(60) NOT NULL,
    CONSTRAINT uq_user_permission UNIQUE (user_id, permission)
);

-- ADMIN (okrug darajasi): foydalanuvchilarni boshqarish + eski "Harbiy okrug mas'uli" vakolatlari.
INSERT INTO role_permissions (role, permission) VALUES
    ('ADMIN', 'ADMIN'),
    ('ADMIN', 'SOLDIER_READ'),
    ('ADMIN', 'QUESTIONNAIRE_READ'),
    ('ADMIN', 'ASSIGNMENT_READ'),
    ('ADMIN', 'ASSIGNMENT_PROPOSE'),
    ('ADMIN', 'RESULT_READ'),
    ('ADMIN', 'ADMISSION_READ'),
    ('ADMIN', 'EMPLOYMENT'),
    ('ADMIN', 'GROUP_READ'),
    ('ADMIN', 'REPORTS'),
    ('ADMIN', 'DASHBOARD_VOCATIONAL'),
    ('ADMIN', 'DASHBOARD_OTM'),
    ('ADMIN', 'DASHBOARD_SURVEYS');

-- USER (qism darajasi): barcha eski qism rollarining umumiy qismi. Qolgan vakolatlar — shaxsiy ruxsat orqali.
INSERT INTO role_permissions (role, permission) VALUES
    ('USER', 'GROUP_READ');

-- ---------------------------------------------------------------------------------------------------------
-- 4. Eski qism rollaridagi foydalanuvchilarning o'ziga xos vakolatlarini shaxsiy ruxsat sifatida saqlab qolish
-- ---------------------------------------------------------------------------------------------------------
CREATE TABLE legacy_role_permissions (
    role       VARCHAR(40) NOT NULL,
    permission VARCHAR(60) NOT NULL
);

INSERT INTO legacy_role_permissions (role, permission) VALUES
    ('UNIT_COMMANDER', 'SOLDIER_READ'),
    ('UNIT_COMMANDER', 'SOLDIER_WRITE'),
    ('UNIT_COMMANDER', 'QUESTIONNAIRE_READ'),
    ('UNIT_COMMANDER', 'QUESTIONNAIRE_WRITE'),
    ('UNIT_COMMANDER', 'ATTACHMENT_WRITE'),
    ('UNIT_COMMANDER', 'ASSIGNMENT_READ'),
    ('UNIT_COMMANDER', 'ASSIGNMENT_PROPOSE'),
    ('UNIT_COMMANDER', 'RESULT_READ'),
    ('UNIT_COMMANDER', 'RESULT_WRITE'),
    ('UNIT_COMMANDER', 'ADMISSION_READ'),
    ('UNIT_COMMANDER', 'ADMISSION_WRITE'),
    ('UNIT_COMMANDER', 'EMPLOYMENT'),
    ('UNIT_COMMANDER', 'TRANSFER'),
    ('UNIT_COMMANDER', 'GROUP_WRITE'),
    ('UNIT_COMMANDER', 'GROUP_LEADER_ASSIGN'),
    ('UNIT_COMMANDER', 'SCHEDULE_WRITE'),
    ('UNIT_COMMANDER', 'SCHEDULE_TIME_OVERRIDE'),
    ('UNIT_COMMANDER', 'UNIT_DIRECTIONS'),
    ('UNIT_COMMANDER', 'REPORTS'),
    ('UNIT_COMMANDER', 'DASHBOARD_VOCATIONAL'),
    ('UNIT_COMMANDER', 'DASHBOARD_OTM'),
    ('UNIT_COMMANDER', 'DASHBOARD_SURVEYS'),

    ('UNIT_OPERATOR', 'SOLDIER_READ'),
    ('UNIT_OPERATOR', 'SOLDIER_WRITE'),
    ('UNIT_OPERATOR', 'QUESTIONNAIRE_READ'),
    ('UNIT_OPERATOR', 'ATTACHMENT_WRITE'),
    ('UNIT_OPERATOR', 'ASSIGNMENT_READ'),
    ('UNIT_OPERATOR', 'ASSIGNMENT_PROPOSE'),
    ('UNIT_OPERATOR', 'RESULT_READ'),
    ('UNIT_OPERATOR', 'RESULT_WRITE'),
    ('UNIT_OPERATOR', 'ADMISSION_READ'),
    ('UNIT_OPERATOR', 'ADMISSION_WRITE'),
    ('UNIT_OPERATOR', 'EMPLOYMENT'),
    ('UNIT_OPERATOR', 'GROUP_WRITE'),
    ('UNIT_OPERATOR', 'SCHEDULE_WRITE'),
    ('UNIT_OPERATOR', 'UNIT_DIRECTIONS'),
    ('UNIT_OPERATOR', 'REPORTS'),
    ('UNIT_OPERATOR', 'DASHBOARD_VOCATIONAL'),
    ('UNIT_OPERATOR', 'DASHBOARD_OTM'),
    ('UNIT_OPERATOR', 'DASHBOARD_SURVEYS'),

    ('COMBAT_TRAINING_DEPT', 'RESULT_READ'),
    ('COMBAT_TRAINING_DEPT', 'REPORTS'),
    ('COMBAT_TRAINING_DEPT', 'DASHBOARD_VOCATIONAL'),

    ('EDUCATION_DEPT', 'RESULT_READ'),
    ('EDUCATION_DEPT', 'ADMISSION_READ'),
    ('EDUCATION_DEPT', 'REPORTS'),
    ('EDUCATION_DEPT', 'DASHBOARD_OTM'),

    ('GROUP_LEADER', 'SOLDIER_READ'),

    ('PSYCHOLOGIST', 'SOLDIER_READ'),
    ('PSYCHOLOGIST', 'SOLDIER_WRITE'),
    ('PSYCHOLOGIST', 'QUESTIONNAIRE_READ'),
    ('PSYCHOLOGIST', 'QUESTIONNAIRE_WRITE'),
    ('PSYCHOLOGIST', 'ATTACHMENT_WRITE'),
    ('PSYCHOLOGIST', 'DASHBOARD_SURVEYS');

INSERT INTO user_permissions (user_id, permission)
SELECT u.id, lrp.permission
FROM app_users u
JOIN legacy_role_permissions lrp ON lrp.role = u.role;

DROP TABLE legacy_role_permissions;

-- ---------------------------------------------------------------------------------------------------------
-- 5. Rollarni ko'chirish: respublika -> SUPER_ADMIN, okrug -> ADMIN, qism -> USER
-- ---------------------------------------------------------------------------------------------------------
UPDATE app_users SET role = 'SUPER_ADMIN' WHERE role IN ('SYSTEM_ADMIN', 'HKTB', 'JTB', 'TMIBB');
UPDATE app_users SET role = 'ADMIN' WHERE role = 'DISTRICT_OFFICER';
UPDATE app_users SET role = 'USER'
WHERE role IN ('UNIT_COMMANDER', 'UNIT_OPERATOR', 'COMBAT_TRAINING_DEPT', 'EDUCATION_DEPT', 'GROUP_LEADER',
               'PSYCHOLOGIST');

-- Respublika darajasidagi rollar hududga biriktirilmaydi.
UPDATE app_users SET location_id = NULL WHERE role IN ('SUPER_ADMIN', 'MEGA_SUPER_ADMIN');

UPDATE deadlines SET responsible_role = 'SUPER_ADMIN' WHERE responsible_role IN ('SYSTEM_ADMIN', 'HKTB', 'JTB', 'TMIBB');
UPDATE deadlines SET responsible_role = 'ADMIN' WHERE responsible_role = 'DISTRICT_OFFICER';
UPDATE deadlines SET responsible_role = 'USER'
WHERE responsible_role IN ('UNIT_COMMANDER', 'UNIT_OPERATOR', 'COMBAT_TRAINING_DEPT', 'EDUCATION_DEPT',
                           'GROUP_LEADER', 'PSYCHOLOGIST');

UPDATE deadlines SET escalation_role = 'SUPER_ADMIN' WHERE escalation_role IN ('SYSTEM_ADMIN', 'HKTB', 'JTB', 'TMIBB');
UPDATE deadlines SET escalation_role = 'ADMIN' WHERE escalation_role = 'DISTRICT_OFFICER';
UPDATE deadlines SET escalation_role = 'USER'
WHERE escalation_role IN ('UNIT_COMMANDER', 'UNIT_OPERATOR', 'COMBAT_TRAINING_DEPT', 'EDUCATION_DEPT',
                          'GROUP_LEADER', 'PSYCHOLOGIST');
