-- Guruh kattasi endi tizim foydalanuvchisi emas, alohida ma'lumot yozuvi (o'qituvchi kabi).
CREATE TABLE group_leaders (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name        VARCHAR(200) NOT NULL,
    military_rank    VARCHAR(100),
    phone            VARCHAR(40),
    military_unit_id BIGINT       NOT NULL REFERENCES military_units (id)
);

ALTER TABLE study_groups ADD COLUMN leader_id BIGINT REFERENCES group_leaders (id);

-- Mavjud guruh kattalarini (foydalanuvchilar) yangi jadvalga ko'chirish; foydalanuvchi hisoblari o'zgarmaydi.
INSERT INTO group_leaders (full_name, military_unit_id)
SELECT DISTINCT u.full_name, l.military_unit_id
FROM app_users u
JOIN locations l ON l.id = u.location_id
WHERE l.military_unit_id IS NOT NULL
  AND u.id IN (SELECT leader_user_id FROM study_groups WHERE leader_user_id IS NOT NULL);

UPDATE study_groups g
SET leader_id = (SELECT MIN(gl.id)
                 FROM group_leaders gl
                 JOIN app_users u ON u.full_name = gl.full_name
                 JOIN locations l ON l.id = u.location_id AND l.military_unit_id = gl.military_unit_id
                 WHERE u.id = g.leader_user_id)
WHERE g.leader_user_id IS NOT NULL;

ALTER TABLE study_groups DROP COLUMN leader_user_id;
