-- "Askar ta'limi" MVP sxemasi (TT 8-bo'lim)

CREATE TABLE regions (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE districts (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id BIGINT       NOT NULL REFERENCES regions (id),
    name      VARCHAR(120) NOT NULL,
    CONSTRAINT uq_district UNIQUE (region_id, name)
);

CREATE TABLE military_districts (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30)  NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL
);

CREATE TABLE military_units (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    military_district_id BIGINT       NOT NULL REFERENCES military_districts (id),
    code                 VARCHAR(30)  NOT NULL UNIQUE,
    name                 VARCHAR(160) NOT NULL
);

CREATE TABLE app_users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username             VARCHAR(60)  NOT NULL UNIQUE,
    password_hash        VARCHAR(100) NOT NULL,
    full_name            VARCHAR(160) NOT NULL,
    role                 VARCHAR(40)  NOT NULL,
    military_district_id BIGINT REFERENCES military_districts (id),
    military_unit_id     BIGINT REFERENCES military_units (id),
    active               BOOLEAN      NOT NULL DEFAULT TRUE,
    failed_attempts      INT          NOT NULL DEFAULT 0,
    locked_until         TIMESTAMP
);

CREATE TABLE dictionary_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(40)  NOT NULL,
    code        VARCHAR(60)  NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    hours       INT,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order  INT          NOT NULL DEFAULT 0,
    CONSTRAINT uq_dictionary_code UNIQUE (type, code)
);

-- Qism uchun faollashtirilgan kasb yo'nalishlari (anketa 14-savol)
CREATE TABLE unit_directions (
    military_unit_id BIGINT NOT NULL REFERENCES military_units (id),
    direction_id     BIGINT NOT NULL REFERENCES dictionary_items (id),
    PRIMARY KEY (military_unit_id, direction_id)
);

CREATE TABLE education_institutions (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type      VARCHAR(30)  NOT NULL,
    name      VARCHAR(255) NOT NULL,
    region_id BIGINT REFERENCES regions (id)
);

CREATE TABLE soldiers (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinfl                  VARCHAR(14)  NOT NULL UNIQUE,
    full_name              VARCHAR(200) NOT NULL,
    birth_date             DATE         NOT NULL,
    passport               VARCHAR(12)  NOT NULL,
    phone                  VARCHAR(20)  NOT NULL,
    phone_kinship_id       BIGINT REFERENCES dictionary_items (id),
    region_id              BIGINT       NOT NULL REFERENCES regions (id),
    district_id            BIGINT       NOT NULL REFERENCES districts (id),
    mahalla                VARCHAR(160),
    street                 VARCHAR(160),
    house                  VARCHAR(30),
    apartment              VARCHAR(30),
    military_unit_id       BIGINT       NOT NULL REFERENCES military_units (id),
    conscription_date      DATE,
    service_end_date       DATE,
    general_education      VARCHAR(30)  NOT NULL,
    professional_education VARCHAR(30),
    higher_education       VARCHAR(30),
    prior_occupation       VARCHAR(255),
    no_prior_occupation    BOOLEAN      NOT NULL DEFAULT FALSE,
    trainable              BOOLEAN,
    cycle_year             INT          NOT NULL,
    created_at             TIMESTAMP    NOT NULL,
    updated_at             TIMESTAMP    NOT NULL
);
CREATE INDEX ix_soldiers_unit ON soldiers (military_unit_id);
CREATE INDEX ix_soldiers_name ON soldiers (full_name);

CREATE TABLE soldier_field_sources (
    soldier_id BIGINT      NOT NULL REFERENCES soldiers (id) ON DELETE CASCADE,
    field_name VARCHAR(60) NOT NULL,
    source     VARCHAR(20) NOT NULL,
    filled_by  VARCHAR(60) NOT NULL,
    filled_at  TIMESTAMP   NOT NULL,
    PRIMARY KEY (soldier_id, field_name)
);

CREATE TABLE soldier_certificates (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    soldier_id         BIGINT      NOT NULL REFERENCES soldiers (id) ON DELETE CASCADE,
    kind               VARCHAR(20) NOT NULL,
    dictionary_item_id BIGINT REFERENCES dictionary_items (id),
    title              VARCHAR(255),
    level              VARCHAR(60)
);

CREATE TABLE soldier_awards (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    soldier_id BIGINT      NOT NULL REFERENCES soldiers (id) ON DELETE CASCADE,
    kind_id    BIGINT      NOT NULL REFERENCES dictionary_items (id),
    place      VARCHAR(20) NOT NULL
);

CREATE TABLE questionnaires (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    soldier_id            BIGINT      NOT NULL REFERENCES soldiers (id),
    cycle_year            INT         NOT NULL,
    status                VARCHAR(20) NOT NULL,
    psychologist_id       BIGINT      NOT NULL REFERENCES app_users (id),
    filled_date           DATE        NOT NULL,
    interest_direction_id BIGINT REFERENCES dictionary_items (id),
    interest_other_text   VARCHAR(255),
    plan_other_text       VARCHAR(255),
    other_subject_text    VARCHAR(255),
    updated_at            TIMESTAMP   NOT NULL,
    CONSTRAINT uq_questionnaire_cycle UNIQUE (soldier_id, cycle_year)
);

CREATE TABLE questionnaire_plans (
    questionnaire_id BIGINT NOT NULL REFERENCES questionnaires (id) ON DELETE CASCADE,
    plan_id          BIGINT NOT NULL REFERENCES dictionary_items (id),
    PRIMARY KEY (questionnaire_id, plan_id)
);

CREATE TABLE questionnaire_university_choices (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    questionnaire_id BIGINT       NOT NULL REFERENCES questionnaires (id) ON DELETE CASCADE,
    priority         INT          NOT NULL,
    university       VARCHAR(255) NOT NULL,
    study_direction  VARCHAR(255) NOT NULL
);

CREATE TABLE questionnaire_specialty_subjects (
    questionnaire_id BIGINT NOT NULL REFERENCES questionnaires (id) ON DELETE CASCADE,
    subject_id       BIGINT NOT NULL REFERENCES dictionary_items (id),
    PRIMARY KEY (questionnaire_id, subject_id)
);

CREATE TABLE questionnaire_mandatory_subjects (
    questionnaire_id BIGINT NOT NULL REFERENCES questionnaires (id) ON DELETE CASCADE,
    subject_id       BIGINT NOT NULL REFERENCES dictionary_items (id),
    PRIMARY KEY (questionnaire_id, subject_id)
);

CREATE TABLE teachers (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name         VARCHAR(200) NOT NULL,
    specialty         VARCHAR(255) NOT NULL,
    institution_id    BIGINT       NOT NULL REFERENCES education_institutions (id),
    military_unit_id  BIGINT       NOT NULL REFERENCES military_units (id),
    access_order_no   VARCHAR(60),
    access_valid_until DATE
);

CREATE TABLE study_groups (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(160) NOT NULL,
    type              VARCHAR(20)  NOT NULL,
    military_unit_id  BIGINT       NOT NULL REFERENCES military_units (id),
    institution_id    BIGINT REFERENCES education_institutions (id),
    profession_id     BIGINT REFERENCES dictionary_items (id),
    start_date        DATE         NOT NULL,
    end_date          DATE         NOT NULL,
    classroom         VARCHAR(80),
    leader_user_id    BIGINT REFERENCES app_users (id),
    leader_order_no   VARCHAR(60),
    leader_order_date DATE,
    cycle_year        INT          NOT NULL
);

CREATE TABLE group_subjects (
    group_id   BIGINT NOT NULL REFERENCES study_groups (id) ON DELETE CASCADE,
    subject_id BIGINT NOT NULL REFERENCES dictionary_items (id),
    PRIMARY KEY (group_id, subject_id)
);

CREATE TABLE group_soldiers (
    group_id   BIGINT NOT NULL REFERENCES study_groups (id) ON DELETE CASCADE,
    soldier_id BIGINT NOT NULL REFERENCES soldiers (id),
    PRIMARY KEY (group_id, soldier_id)
);

CREATE TABLE group_teachers (
    group_id   BIGINT NOT NULL REFERENCES study_groups (id) ON DELETE CASCADE,
    teacher_id BIGINT NOT NULL REFERENCES teachers (id),
    PRIMARY KEY (group_id, teacher_id)
);

CREATE TABLE lessons (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id            BIGINT      NOT NULL REFERENCES study_groups (id) ON DELETE CASCADE,
    lesson_date         DATE        NOT NULL,
    start_time          TIME        NOT NULL,
    end_time            TIME        NOT NULL,
    academic_hours      INT         NOT NULL,
    topic               VARCHAR(255),
    kind                VARCHAR(20) NOT NULL,
    status              VARCHAR(20) NOT NULL,
    change_reason       VARCHAR(255),
    teacher_present     BOOLEAN,
    attendance_recorded BOOLEAN     NOT NULL DEFAULT FALSE,
    attendance_recorded_at TIMESTAMP
);
CREATE INDEX ix_lessons_group_date ON lessons (group_id, lesson_date);
CREATE INDEX ix_lessons_date ON lessons (lesson_date);

CREATE TABLE attendances (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id   BIGINT      NOT NULL REFERENCES lessons (id) ON DELETE CASCADE,
    soldier_id  BIGINT      NOT NULL REFERENCES soldiers (id),
    status      VARCHAR(20) NOT NULL,
    reason      VARCHAR(30),
    recorded_by VARCHAR(60) NOT NULL,
    CONSTRAINT uq_attendance UNIQUE (lesson_id, soldier_id)
);

CREATE TABLE audit_logs (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at        TIMESTAMP    NOT NULL,
    username  VARCHAR(60)  NOT NULL,
    action    VARCHAR(40)  NOT NULL,
    entity    VARCHAR(60)  NOT NULL,
    entity_id VARCHAR(60),
    details   VARCHAR(1000)
);
CREATE INDEX ix_audit_at ON audit_logs (at);

CREATE TABLE app_settings (
    setting_key   VARCHAR(80)  PRIMARY KEY,
    setting_value VARCHAR(255) NOT NULL
);
