CREATE TABLE subdivisions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    military_unit_id BIGINT       NOT NULL REFERENCES military_units (id),
    parent_id        BIGINT REFERENCES subdivisions (id),
    name             VARCHAR(160) NOT NULL
);
CREATE INDEX ix_subdivisions_unit ON subdivisions (military_unit_id);

ALTER TABLE soldiers ADD COLUMN subdivision_id BIGINT REFERENCES subdivisions (id);

CREATE TABLE soldier_transfers (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    soldier_id           BIGINT       NOT NULL REFERENCES soldiers (id) ON DELETE CASCADE,
    from_unit_id         BIGINT       NOT NULL REFERENCES military_units (id),
    to_unit_id           BIGINT       NOT NULL REFERENCES military_units (id),
    from_subdivision_id  BIGINT REFERENCES subdivisions (id),
    to_subdivision_id    BIGINT REFERENCES subdivisions (id),
    reason               VARCHAR(255) NOT NULL,
    transferred_at       TIMESTAMP    NOT NULL,
    transferred_by       VARCHAR(60)  NOT NULL
);

CREATE TABLE attachments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_type   VARCHAR(30)  NOT NULL,
    owner_id     BIGINT       NOT NULL,
    kind         VARCHAR(120),
    file_name    VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes   BIGINT       NOT NULL,
    storage_name VARCHAR(80)  NOT NULL,
    uploaded_by  VARCHAR(60)  NOT NULL,
    uploaded_at  TIMESTAMP    NOT NULL
);
CREATE INDEX ix_attachments_owner ON attachments (owner_type, owner_id);
