CREATE TABLE assignments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    military_unit_id  BIGINT       NOT NULL REFERENCES military_units (id),
    institution_id    BIGINT       NOT NULL REFERENCES education_institutions (id),
    direction         VARCHAR(20)  NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    basis_document    VARCHAR(255),
    valid_from        DATE,
    valid_to          DATE,
    contract_no       VARCHAR(60),
    contract_date     DATE,
    joint_plan        VARCHAR(500),
    proposal_note     VARCHAR(500),
    decision_note     VARCHAR(500),
    proposed_by       VARCHAR(60)  NOT NULL,
    decided_by        VARCHAR(60),
    created_at        TIMESTAMP    NOT NULL,
    cycle_year        INT          NOT NULL
);
CREATE INDEX ix_assignments_unit ON assignments (military_unit_id);

CREATE TABLE facilities (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    military_unit_id BIGINT       NOT NULL REFERENCES military_units (id),
    name             VARCHAR(160) NOT NULL,
    kind             VARCHAR(30)  NOT NULL,
    capacity         INT,
    condition_state  VARCHAR(20)  NOT NULL,
    equipment        VARCHAR(500),
    shortages        VARCHAR(500),
    survey_date      DATE
);
CREATE INDEX ix_facilities_unit ON facilities (military_unit_id);

CREATE TABLE facility_suitable (
    facility_id BIGINT NOT NULL REFERENCES facilities (id) ON DELETE CASCADE,
    item_id     BIGINT NOT NULL REFERENCES dictionary_items (id),
    PRIMARY KEY (facility_id, item_id)
);

ALTER TABLE study_groups ADD COLUMN facility_id BIGINT REFERENCES facilities (id);
