CREATE TABLE notifications (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES app_users (id) ON DELETE CASCADE,
    title        VARCHAR(160) NOT NULL,
    body         VARCHAR(500) NOT NULL,
    link         VARCHAR(160),
    is_read      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP    NOT NULL
);
CREATE INDEX ix_notifications_user ON notifications (user_id, is_read);

CREATE TABLE deadlines (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(200) NOT NULL,
    description        VARCHAR(500),
    deadline_date      DATE         NOT NULL,
    responsible_role   VARCHAR(40)  NOT NULL,
    escalation_role    VARCHAR(40)  NOT NULL,
    remind_days_before INT          NOT NULL DEFAULT 7,
    status             VARCHAR(10)  NOT NULL,
    last_reminder_on   DATE,
    escalated          BOOLEAN      NOT NULL DEFAULT FALSE,
    cycle_year         INT          NOT NULL
);
