CREATE TABLE admissions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    soldier_id            BIGINT      NOT NULL REFERENCES soldiers (id) ON DELETE CASCADE,
    cycle_year            INT         NOT NULL,
    bmba_registered       BOOLEAN     NOT NULL DEFAULT FALSE,
    benefits_uploaded     BOOLEAN     NOT NULL DEFAULT FALSE,
    test_participated     BOOLEAN     NOT NULL DEFAULT FALSE,
    test_score            DOUBLE PRECISION,
    admitted              BOOLEAN     NOT NULL DEFAULT FALSE,
    university            VARCHAR(255),
    study_direction       VARCHAR(255),
    study_form            VARCHAR(20),
    online_status         VARCHAR(20) NOT NULL DEFAULT 'NONE',
    bmba_synced_at        TIMESTAMP,
    updated_at            TIMESTAMP   NOT NULL,
    updated_by            VARCHAR(60) NOT NULL,
    CONSTRAINT uq_admission UNIQUE (soldier_id, cycle_year)
);
