CREATE TABLE employment_lists (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id     BIGINT REFERENCES regions (id),
    agency        VARCHAR(200) NOT NULL,
    soldier_count INT          NOT NULL,
    format        VARCHAR(10)  NOT NULL,
    generated_at  TIMESTAMP    NOT NULL,
    generated_by  VARCHAR(60)  NOT NULL,
    cycle_year    INT          NOT NULL
);
INSERT INTO app_settings (setting_key, setting_value) VALUES ('employment.monthsBeforeEnd', '1');
