export const adminLabels = {
  users: {
    title: 'Foydalanuvchilar',
    subtitle: 'Rollar va vakolat doiralarini boshqarish',
    confirmDelete: "Foydalanuvchi o'chirilsinmi? Bu amalni qaytarib bo'lmaydi",
    deleted: "Foydalanuvchi o'chirildi",
    addHint: "Yangi foydalanuvchi «Hududlar» sahifasida, tegishli hudud qatorida qo'shiladi",
    editTitle: 'Foydalanuvchini tahrirlash',
    username: 'Login',
    selfRenamed: 'Login o\'zgartirildi. Yangi login bilan qayta kiring',
    password: 'Parol',
    passwordHint: 'Kamida 8 belgi: bosh harf, kichik harf va raqam',
    newPassword: 'Yangi parol (o\'zgartirish uchun)',
    role: 'Rol',
    location: 'Hudud',
    district: 'Harbiy okrug',
    unit: 'Harbiy qism',
  },
  userPermissions: {
    title: 'Shaxsiy ruxsatlar',
    hint: "Rol orqali berilgan ruxsatlar belgilangan va o'zgartirilmaydi (ularni «Rol huquqlari» sahifasida sozlang). Qo'shimcha ruxsatlarni shu yerda bering.",
    byRole: 'Rol orqali',
    save: 'Ruxsatlarni saqlash',
    saved: 'Shaxsiy ruxsatlar saqlandi',
  },
  locations: {
    title: 'Hududlar',
    subtitle: "Vazirlik, harbiy okruglar va harbiy qismlar daraxti",
    add: "Okrug qo'shish",
    addUnit: "Qism qo'shish",
    createDistrict: "Yangi harbiy okrug",
    createUnit: "Yangi harbiy qism",
    edit: 'Hududni tahrirlash',
    name: 'Nomi',
    code: 'Kodi',
    level: 'Daraja',
    levels: { REPUBLIC: 'Vazirlik', DISTRICT: 'Harbiy okrug', UNIT: 'Harbiy qism' },
    confirmDelete: "Hudud o'chirilsinmi? Bu amalni qaytarib bo'lmaydi",
    deleted: "Hudud o'chirildi",
    parentDistrict: 'Okrug',
    users: 'Foydalanuvchilar',
    addUser: "Foydalanuvchi qo'shish",
    createUserFor: (locationName: string) => `Yangi foydalanuvchi: ${locationName}`,
    withUser: "Shu hudud uchun foydalanuvchi ham qo'shish",
    userCreated: "Foydalanuvchi qo'shildi",
    userFailed: (reason: string) => `Hudud qo'shildi, lekin foydalanuvchi qo'shilmadi: ${reason}. Uni hudud qatoridan qo'shing`,
    noRole: "Bu daraja uchun rol topilmadi",
  },
  audit: {
    title: 'Audit jurnali',
    subtitle: "Kim, qachon, qaysi yozuvni o'zgartirdi",
    at: 'Vaqt',
    user: 'Foydalanuvchi',
    action: 'Amal',
    entity: 'Obyekt',
    details: 'Tafsilot',
    filterUser: 'Foydalanuvchi bo\'yicha',
    filterEntity: 'Obyekt bo\'yicha',
  },
  integrations: {
    title: 'Integratsiya jurnali',
    subtitle: "Manba tizim va BMBA ga har bir murojaat: vaqti, holati, xatosi",
    at: 'Vaqt', system: 'Tizim', operation: 'Amal', reference: 'Havola', status: 'Holat', message: 'Xabar', duration: 'ms', actor: 'Kim',
  },
  cycles: {
    title: 'Yillik sikllar',
    open: 'Yangi sikl ochish',
    close: 'Yopish',
    reopen: 'Qayta ochish',
    confirmReopen: 'Yopilgan sikl qayta ochilsinmi? Yangi askar va guruh qo\'shish yana mumkin bo\'ladi.',
    year: 'Yil', status: 'Holat', opened: 'Ochilgan', closed: 'Yopilgan',
    confirmClose: "Sikl yopilsa, yangi askar va guruh qo'shib bo'lmaydi. Yopilsinmi?",
    hint: 'Yopiq siklda yangi askar va guruh yaratilmaydi',
  },
  retention: {
    title: 'Saqlash muddati',
    run: 'Tekshiruvni hozir ishga tushirish',
    result: (w: number, a: number) => `Ogohlantirilgan: ${w}, anonimlashtirilgan: ${a}`,
    hint: "Muddat tugagan askarlar ma'lumotlari ogohlantirishdan 7 kun keyin anonimlashtiriladi (statistika saqlanadi)",
  },
  settings: {
    title: 'Tizim sozlamalari',
    subtitle: 'Anketa, dars vaqti, bandlik va saqlash muddati sozlamalari',
    saved: 'Sozlamalar saqlandi',
    reset: 'Bekor qilish',
    unsaved: "Saqlanmagan o'zgarishlar bor",
    groups: {
      survey: 'Anketa',
      employment: 'Bandlik',
      retention: "Ma'lumotlarni saqlash",
      other: 'Boshqa',
    },
    labels: {
      'survey.futurePlan.mode': 'Anketa 15-savol tanlov rejimi',
      'employment.monthsBeforeEnd': "Bandlik ro'yxati: xizmat tugashiga necha oy qolganda",
      'retention.years': "Ma'lumotlarni saqlash muddati (yil; 0 — o'chirilgan)",
    } as Record<string, string>,
    modes: { MULTIPLE: 'Bir nechta variant', SINGLE: 'Bitta variant' },
  },
} as const;
