export const adminLabels = {
  users: {
    title: 'Foydalanuvchilar',
    subtitle: 'Rollar va vakolat doiralarini boshqarish',
    add: "Foydalanuvchi qo'shish",
    editTitle: 'Foydalanuvchini tahrirlash',
    createTitle: "Yangi foydalanuvchi",
    username: 'Login',
    password: 'Parol',
    passwordHint: 'Kamida 8 belgi: bosh harf, kichik harf va raqam',
    newPassword: 'Yangi parol (o\'zgartirish uchun)',
    role: 'Rol',
    district: 'Harbiy okrug',
    unit: 'Harbiy qism',
  },
  audit: {
    title: 'Audit jurnali',
    subtitle: "Kim, qachon, qaysi yozuvni o'zgartirdi",
    at: 'Vaqt',
    user: 'Foydalanuvchi',
    action: 'Amal',
    entity: 'Obyekt',
    details: 'Tafsilot',
    filterUser: 'Foydalanuvchi bo\'yicha',
    filterEntity: 'Obyekt bo\'yicha',
  },
  integrations: {
    title: 'Integratsiya jurnali',
    subtitle: "Manba tizim, BMBA va KTA ga har bir murojaat: vaqti, holati, xatosi",
    at: 'Vaqt', system: 'Tizim', operation: 'Amal', reference: 'Havola', status: 'Holat', message: 'Xabar', duration: 'ms', actor: 'Kim',
  },
  cycles: {
    title: 'Yillik sikllar',
    open: 'Yangi sikl ochish',
    close: 'Yopish',
    year: 'Yil', status: 'Holat', opened: 'Ochilgan', closed: 'Yopilgan',
    confirmClose: "Sikl yopilsa, yangi askar va guruh qo'shib bo'lmaydi. Yopilsinmi?",
    hint: 'Yopiq siklda yangi askar va guruh yaratilmaydi',
  },
  retention: {
    title: 'Saqlash muddati',
    run: 'Tekshiruvni hozir ishga tushirish',
    result: (w: number, a: number) => `Ogohlantirilgan: ${w}, anonimlashtirilgan: ${a}`,
    hint: "Muddat tugagan askarlar ma'lumotlari ogohlantirishdan 7 kun keyin anonimlashtiriladi (statistika saqlanadi)",
  },
  settings: {
    title: 'Tizim sozlamalari',
    subtitle: 'Anketa, davomat va dars vaqti sozlamalari',
    saved: 'Sozlamalar saqlandi',
    labels: {
      'survey.futurePlan.mode': 'Anketa 15-savol tanlov rejimi',
      'attendance.editHours': 'Davomatni tahrirlash muddati (soat)',
      'lesson.defaultStart': 'Standart dars boshlanishi',
      'lesson.defaultEnd': 'Standart dars tugashi',
      'lesson.defaultAcademicHours': "Standart o'quv soatlari",
      'employment.monthsBeforeEnd': "Bandlik ro'yxati: xizmat tugashiga necha oy qolganda",
      'retention.years': "Ma'lumotlarni saqlash muddati (yil; 0 — o'chirilgan)",
      'security.2fa.required': "Respublika/okrug rollari uchun 2FA majburiy (true/false)",
    } as Record<string, string>,
    modes: { MULTIPLE: 'Bir nechta variant', SINGLE: 'Bitta variant' },
  },
} as const;
