export const surveyLabels = {
  title: 'Elektron anketa',
  subtitle: "Muddatli harbiy xizmatchilarning kasbiy ko'nikma va qiziqishlarini o'rganish bo'yicha anketa",
  status: { DRAFT: 'Qoralama', FINALIZED: 'Yakunlangan' },
  header: { date: "To'ldirilgan sana", district: 'Harbiy okrug', unit: 'Harbiy qism', psychologist: 'Psixolog' },
  sections: {
    interests: 'IV. Qiziqishlari',
    higher: "V. Oliy ta'lim borasidagi rejalari",
    higherLocked: "V bo'lim faqat 15-savolda \"Oliy ta'limga o'qishga kirish\" tanlanganda ochiladi va majburiy bo'ladi",
  },
  q14: "14. Sizni ko'proq qiziqtiradigan bitta kasb yo'nalishi",
  q15: '15. Kelgusida nima ish bilan shug\'ullanmoqchisiz?',
  q16: "16. Qaysi OTM va ta'lim yo'nalishiga hujjat topshirasiz? (3 tagacha, ustuvorlik tartibida)",
  q17: "17. Tanlangan yo'nalish uchun ixtisoslik fanlari",
  q18: "18. Majburiy fanlarning qaysi biridan qo'shimcha tayyorgarlik zarur?",
  otherText: 'Yozing',
  university: 'OTM nomi',
  studyDirection: "Ta'lim yo'nalishi",
  addChoice: "Yana OTM qo'shish",
  priority: (n: number) => `${n}-ustuvor`,
  actions: { finalize: 'Yakunlash', print: 'PDF / chop etish' },
  suggestions: { title: 'Guruhlarga taqsimot taklifi', hint: "Bir xil kasb yo'nalishini tanlaganlar bitta kasb guruhiga, bir xil majburiy fanni belgilaganlar tegishli fan guruhiga taklif qilinadi", direction: "Kasb yo'nalishi", subject: 'Fan' },
  saved: 'Anketa saqlandi',
  finalized: 'Anketa yakunlandi',
  noteFinalized: 'Yakunlangan anketani faqat psixolog yoki qism qo\'mondoni tahrirlashi mumkin. O\'zgarishlar audit jurnalida saqlanadi.',
  noDirections: "Bu qism uchun kasb yo'nalishlari faollashtirilmagan",
  errors: {
    direction: "14-savol: kasb yo'nalishi tanlanmagan",
    directionOther: '14-savol: "Boshqa" uchun matn kiriting',
    plans: '15-savol: kamida bitta variant tanlang',
    planOther: '15-savol: "Boshqa" uchun matn kiriting',
    single: '15-savol: faqat bitta variant tanlanadi',
    choices: '16-savol: OTM va yo\'nalishni kiriting',
    specialty: '17-savol: ixtisoslik fanlarini tanlang',
    mandatory: '18-savol: majburiy fanlarni tanlang',
  },
  print: {
    heading: 'MUDDATLI HARBIY XIZMATCHILARNING KASBIY KO\'NIKMA VA QIZIQISHLARINI O\'RGANISH BO\'YICHA ANKETA',
    soldierSignature: 'Askar imzosi',
    psychologistSignature: 'Psixolog imzosi',
  },
} as const;
