import type { GroupType, InstitutionType } from './types';

export const groupTypeLabels: Record<GroupType, string> = {
  VOCATIONAL: 'Kasb kursi',
  OTM_PREP: 'OTM tayyorlov kursi',
};

export const institutionTypeLabels: Record<InstitutionType, string> = {
  TECHNICAL_SCHOOL: 'Texnikum',
  SCHOOL: 'Maktab',
  TRAINING_CENTER: "O'quv markazi",
};

export const groupLabels = {
  listTitle: 'Guruhlar',
  listSubtitle: 'Kasb kurslari va OTM tayyorlov guruhlari',
  create: 'Yangi guruh',
  createTitle: 'Yangi guruh yaratish',
  editTitle: 'Guruhni tahrirlash',
  columns: {
    name: 'Guruh', type: 'Turi', unit: 'Harbiy qism', curriculum: 'Kasb / fanlar', period: 'Davri',
    members: 'Askarlar', leader: 'Guruh kattasi',
  },
  fields: {
    name: 'Guruh nomi',
    type: 'Guruh turi',
    unit: 'Harbiy qism',
    institution: 'Biriktirilgan muassasa',
    profession: 'Kasb',
    subjects: 'Fanlar',
    startDate: 'Boshlanish sanasi',
    endDate: 'Tugash sanasi',
    classroom: 'Sinf (xona)',
    leader: 'Guruh kattasi',
  },
  vocationalNote: 'Kasb kursi 6 oydan oshmasligi kerak',
  institutionPickUnit: 'Avval harbiy qismni tanlang',
  institutionNoContract: "Bu harbiy qism bilan shartnomasi bor muassasa yo'q. «O'qituvchilar» sahifasida muassasani qismga biriktiring",
  tabs: { info: "Ma'lumot", members: 'Askarlar', teachers: "O'qituvchilar", results: 'Kurs yakuni' },
  noLeader: 'Tayinlanmagan',
  removeLeader: 'Guruh kattasini olib tashlash',
  leaderRemoved: 'Guruh kattasi olib tashlandi',
  confirmDelete: "Guruh o'chirilsinmi? Darslar va natijalar ham o'chadi",
  deleted: "Guruh o'chirildi",
  membersSubdivision: "Bo'linma bo'yicha qidirish",
  membersHint: 'Askar faqat bitta guruhga qo\'shilishi mumkin (shu qismdagi askarlar)',
  teachersHint: "Guruhga biriktiriladigan o'qituvchilar",
  saved: 'Saqlandi',
  leaderForm: {
    section: 'Guruh kattasi',
    hint: "Guruh kattasi tizimga kirmaydi — faqat ma'lumot yozuvi. Bo'sh qoldirsangiz, guruh kattasiz saqlanadi",
    pinfl: 'JShShIR',
    pinflInvalid: "JShShIR 14 ta raqamdan iborat bo'lishi kerak",
    rank: 'Unvoni',
    phone: 'Telefon',
  },
  teachers: {
    title: "O'qituvchilar va muassasalar",
    subtitle: "O'qituvchilar faqat ma'lumot yozuvi — ular tizimga kirmaydi",
    add: "O'qituvchi qo'shish",
    confirmDelete: "O'qituvchi o'chirilsinmi? U barcha guruhlardan ham olib tashlanadi",
    deleted: "O'qituvchi o'chirildi",
    addInstitution: "Muassasa qo'shish",
    editInstitution: 'Muassasani tahrirlash',
    tabTeachers: "O'qituvchilar",
    institutionsTitle: 'Muassasalar',
    confirmDeleteInstitution: "Muassasa o'chirilsinmi?",
    institutionDeleted: "Muassasa o'chirildi",
    specialty: 'Mutaxassisligi',
    editTeacher: "O'qituvchini tahrirlash",
    specialtyPlaceholder: 'Kasb yoki fanni tanlang',
    specialtyGroups: { professions: 'Kasblar', subjects: 'Fanlar' },
    institution: 'Tashkiloti',
    tabContracts: 'Muassasani harbiy qismga biriktirish',
    editContract: 'Biriktirishni tahrirlash',
    addContract: 'Muassasani qismga biriktirish',
    contractTitle: 'Muassasani harbiy qismga biriktirish',
    contractUnit: 'Harbiy qism',
    contractInstitution: 'Muassasa',
    contractDistrict: 'Okrug',
    contractSaved: 'Muassasa harbiy qismga biriktirildi',
    contractDeleted: 'Biriktirish bekor qilindi',
    confirmDeleteContract: 'Biriktirish bekor qilinsinmi?',
    institutionProfessions: "O'qitiladigan kasblar",
    institutionSubjects: "O'qitiladigan fanlar",
    institutionType: 'Muassasa turi',
    institutionName: 'Muassasa nomi',
  },
} as const;
