import type {
  AwardPlace,
  FieldSource,
  GeneralEducation,
  HigherEducation,
  ProfessionalEducation,
} from './types';

export const soldierLabels = {
  listTitle: "Askarlar (yig'ma jild)",
  listSubtitle: 'JShShIR yoki F.I.Sh. bo\'yicha qidiring',
  create: 'Yangi askar',
  searchPlaceholder: 'JShShIR yoki F.I.Sh.',
  editTitle: "Yig'ma jildni tahrirlash",
  createTitle: "Yangi askarni ro'yxatga olish",
  profileTitle: "Askarning yig'ma jildi",
  openQuestionnaire: 'Anketa',
  edit: 'Tahrirlash',
  columns: { pinfl: 'JShShIR', birthDate: "Tug'ilgan sana", unit: 'Harbiy qism', subdivision: "Bo'linma", address: 'Manzil' },
  lookup: {
    title: '1-qadam: JShShIR',
    placeholder: '14 ta raqam',
    button: 'Manba tizimdan olish',
    manual: "Qo'lda kiritish",
    found: "Ma'lumotlar manba tizimdan olindi. Yetishmagan maydonlarni to'ldiring",
    notFound: "Manba tizimda topilmadi. Ma'lumotlarni qo'lda kiriting",
    existing: 'Bu askar tizimda mavjud',
    openExisting: "Yig'ma jildni ochish",
    unavailable: "Manba tizim javob bermadi. Ma'lumotlarni qo'lda kiritishingiz mumkin",
    invalidPinfl: 'JShShIR 14 ta raqamdan iborat bo\'lishi kerak',
  },
  sections: {
    general: "I. Umumiy ma'lumotlar",
    education: "II. Ta'lim ma'lumoti",
    skills: "III. Kasbiy ko'nikmalari",
    service: 'Xizmat ma’lumotlari',
  },
  fields: {
    pinfl: 'JShShIR (PINFL)',
    birthDate: "Tug'ilgan sanasi",
    passport: 'Pasport (ID-karta) seriyasi va raqami',
    passportHint: 'Masalan: AA1234567',
    phone: 'Ota-ona yoki yaqin qarindoshining telefoni',
    phoneHint: '+998901234567',
    kinship: 'Qarindoshlik darajasi',
    region: 'Viloyat',
    district: 'Tuman (shahar)',
    mahalla: 'MFY',
    street: "Ko'cha",
    house: 'Uy',
    apartment: 'Xonadon',
    unit: 'Harbiy qism',
    subdivision: "Bo'linma",
    conscriptionDate: 'Chaqiruv sanasi',
    serviceEndDate: 'Xizmat tugash sanasi',
    generalEducation: "Umumiy o'rta ta'lim",
    professionalEducation: "Professional ta'lim",
    higherEducation: "Oliy ta'lim",
    priorOccupation: 'Xizmatga qadar egallagan kasb/hunari yoki faoliyati',
    noPriorOccupation: "Shug'ullanmagan",
    trainable: "Kasbga o'quvchan",
    languageCertificates: 'Til sertifikati',
    professionCertificates: 'Kasb/hunar sertifikati',
    subjectCertificates: 'Fan sertifikati',
    awards: 'Sovrindorligi',
    language: 'Til',
    level: 'Daraja',
    subject: 'Fan',
    professionTitle: 'Kasb/hunar nomi',
    awardKind: 'Musobaqa turi',
    awardPlace: "O'rin",
    addLanguageCertificate: "Til sertifikati qo'shish",
    addProfessionCertificate: "Kasb sertifikati qo'shish",
    addSubjectCertificate: "Fan sertifikati qo'shish",
    addAward: "Sovrindorlik qo'shish",
  },
  sourceTag: { INTEGRATION: 'integratsiya', MANUAL: "qo'lda" } satisfies Record<FieldSource, string>,
  transfer: {
    button: "Boshqa qism/bo'linmaga o'tkazish",
    title: "Askarni o'tkazish",
    unit: 'Yangi harbiy qism',
    reason: "O'tkazish sababi (buyruq, ehtiyoj ...)",
    done: "Askar o'tkazildi",
    history: "O'tkazish tarixi",
    empty: "O'tkazishlar bo'lmagan",
    from: 'Qayerdan',
    to: 'Qayerga',
    reasonColumn: 'Sabab',
    at: 'Vaqt',
    by: 'Kim',
  },
  refresh: {
    button: 'Manba tizim bilan solishtirish',
    title: "Manba tizimdagi o'zgarishlar",
    none: "Farqlar yo'q — ma'lumotlar manba tizimga mos",
    current: 'Tizimda',
    incoming: 'Manba tizimda',
    apply: 'Tanlanganlarni yangilash',
    applied: 'Yangilandi',
    hint: "Manba tizimdagi ma'lumot avtomatik ustiga yozilmaydi: yangilanadigan maydonlarni o'zingiz tanlang",
  },
  import: {
    button: 'XLSX dan import',
    title: 'Askarlarni ommaviy import qilish',
    template: 'Shablonni yuklab olish',
    pick: 'XLSX faylni tanlang',
    result: (imported: number, errors: number) => `Yuklandi: ${imported}, xatolar: ${errors}`,
    row: 'Qator',
    message: 'Xato',
  },
  subdivisionFilter: "Bo'linma bo'yicha",
  saved: "Yig'ma jild saqlandi",
  pdfNote: 'PDF nusxalarni yuklash keyingi bosqichda qo\'shiladi',
} as const;

export const generalEducationLabels: Record<GeneralEducation, string> = {
  SCHOOL: 'Maktab',
  LYCEUM: 'Akademik litsey',
};

export const professionalEducationLabels: Record<ProfessionalEducation, string> = {
  VOCATIONAL_SCHOOL: 'Kasb-hunar maktabi',
  TECHNICAL_SCHOOL: 'Texnikum',
  COLLEGE: 'Kollej',
};

export const higherEducationLabels: Record<HigherEducation, string> = {
  BACHELOR: 'Bakalavr',
  MASTER: 'Magistratura',
  INCOMPLETE_HIGHER: 'Tugallanmagan oliy',
};

export const awardPlaceLabels: Record<AwardPlace, string> = {
  FIRST: 'I o\'rin',
  SECOND: 'II o\'rin',
  THIRD: 'III o\'rin',
  GRAND_PRIX: 'Gran-pri',
};
